
export const townToCounty = new Map([
  ["Andrijaševci", "vukovarsko srijemska"],
  ["Antunovac", "osjecko baranjska"],
  ["Babina Greda", "vukovarsko srijemska"],
  ["Bakar", "primorsko goranska"],
  ["Bale - Valle", "istarska"],
  ["Barban", "istarska"],
  ["Barilović", "karlovacka"],
  ["Baška", "primorsko goranska"],
  ["Baška Voda", "splitsko dalmatinska"],
  ["Bebrina", "brodsko posavska"],
  ["Bedekovčina", "krapinsko zagorska"],
  ["Bedenica", "zagrebacka"],
  ["Bednja", "varazdinska"],
  ["Beli Manastir", "osjecko baranjska"],
  ["Belica", "medimurska"],
  ["Belišće", "osjecko baranjska"],
  ["Benkovac", "zadarska"],
  ["Berek", "bjelovarsko bilogorska"],
  ["Beretinec", "varazdinska"],
  ["Bibinje", "zadarska"],
  ["Bilice", "sibensko kninska"],
  ["Bilje", "osjecko baranjska"],
  ["Biograd na Moru", "zadarska"],
  ["Biskupija", "sibensko kninska"],
  ["Bistra", "zagrebacka"],
  ["Bizovac", "osjecko baranjska"],
  ["Bjelovar", "bjelovarsko bilogorska"],
  ["Blato", "dubrovacko neretvanska"],
  ["Bogdanovci", "vukovarsko srijemska"],
  ["Bol", "splitsko dalmatinska"],
  ["Borovo", "vukovarsko srijemska"],
  ["Bosiljevo", "karlovacka"],
  ["Bošnjaci", "vukovarsko srijemska"],
  ["Brckovljani", "zagrebacka"],
  ["Brdovec", "zagrebacka"],
  ["Brestovac", "pozega slavonska"],
  ["Breznica", "varazdinska"],
  ["Breznički Hum", "varazdinska"],
  ["Brod Moravice", "primorsko goranska"],
  ["Brodski Stupnik", "brodsko posavska"],
  ["Brtonigla - Verteneglio", "istarska"],
  ["Bukovlje", "brodsko posavska"],
  ["Buzet", "istarska"],
  ["Buje - Buie", "istarska"],
  ["Cavtat", "dubrovacko neretvanska"],
  ["Cerna", "vukovarsko srijemska"],
  ["Cestica", "varazdinska"],
  ["Cetingrad", "karlovacka"],
  ["Cista Provo", "splitsko dalmatinska"],
  ["Crikvenica", "primorsko goranska"],
  ["Cres", "primorsko goranska"],
  ["Crnac", "viroviticko podravska"],
  ["Čabar", "primorsko goranska"],
  ["Čačinci", "viroviticko podravska"],
  ["Čađavica", "viroviticko podravska"],
  ["Čaglin", "pozega slavonska"],
  ["Čakovec", "medimurska"],
  ["Čavle", "primorsko goranska"],
  ["Čazma", "bjelovarsko bilogorska"],
  ["Čeminac", "osjecko baranjska"],
  ["Čepin", "osjecko baranjska"],
  ["Čaglin", "pozega slavonska"],
  ["Darda", "osjecko baranjska"],
  ["Daruvar", "bjelovarsko bilogorska"],
  ["Davor", "brodsko posavska"],
  ["Delnice", "primorsko goranska"],
  ["Desinić", "krapinsko zagorska"],
  ["Dežanovac", "bjelovarsko bilogorska"],
  ["Dicmo", "splitsko dalmatinska"],
  ["Domašinec", "medimurska"],
  ["Donja Dubrava", "medimurska"],
  ["Donja Stubica", "krapinsko zagorska"],
  ["Donja Voća", "varazdinska"],
  ["Donji Andrijevci", "brodsko posavska"],
  ["Donji Kraljevec", "medimurska"],
  ["Donji Kukuruzari", "sisacko moslavacka"],
  ["Donji Lapac", "licko senjska"],
  ["Donji Miholjac", "osjecko baranjska"],
  ["Donji Vidovec", "medimurska"],
  ["Dragalić", "brodsko posavska"],
  ["Draž", "osjecko baranjska"],
  ["Drenovci", "vukovarsko srijemska"],
  ["Dreznik Grad", "karlovacka"],
  ["Drniš", "sibensko kninska"],
  ["Drnje", "koprivnicko krizevacka"],
  ["Dubrovačko primorje", "dubrovacko neretvanska"],
  ["Dubrava", "zagrebacka"],
  ["Dubravica", "zagrebacka"],
  ["Duga Resa", "karlovacka"],
  ["Dugo Selo", "zagrebacka"],
  ["Dugopolje", "splitsko dalmatinska"],
  ["Dvor", "sisacko moslavacka"],
  ["Đakovo", "osjecko baranjska"],
  ["Đelekovec", "koprivnicko krizevacka"],
  ["Đulovac", "bjelovarsko bilogorska"],
  ["Đurđenovac", "osjecko baranjska"],
  ["Đurmanec", "krapinsko zagorska"],
  ["Đurđevac", "koprivnicko krizevacka"],
  ["Ernestinovo", "osjecko baranjska"],
  ["Fažana - Fasana", "istarska"],
  ["Farkaševac", "zagrebacka"],
  ["Feričanci", "osjecko baranjska"],
  ["Funtana - Fontane", "istarska"],
  ["Gala", "splitsko dalmatinska"],
  ["Garešnica", "bjelovarsko bilogorska"],
  ["Garčin", "brodsko posavska"],
  ["Gola", "koprivnicko krizevacka"],
  ["Goričan", "medimurska"],
  ["Goričani", "medimurska"],
  ["Gornja Rijeka", "koprivnicko krizevacka"],
  ["Gornja Stubica", "krapinsko zagorska"],
  ["Gornji Bogićevci", "brodsko posavska"],
  ["Gornji Kneginec", "varazdinska"],
  ["Gornji Mihaljevec", "medimurska"],
  ["Gornji Vakuf", "splitsko dalmatinska"],
  ["Gospić", "licko senjska"],
  ["Gračac", "zadarska"],
  ["Gradac", "splitsko dalmatinska"],
  ["Gradec", "zagrebacka"],
  ["Gradište", "vukovarsko srijemska"],
  ["Gradsko", "viroviticko podravska"],
  ["Grožnjan - Grisignana", "istarska"],
  ["Gundinci", "brodsko posavska"],
  ["Gunja", "vukovarsko srijemska"],
  ["Hlebine", "koprivnicko krizevacka"],
  ["Hrašćina", "krapinsko zagorska"],
  ["Hreljin", "primorsko goranska"],
  ["Hum na Sutli", "krapinsko zagorska"],
  ["Hvar", "splitsko dalmatinska"],
  ["Ilok", "vukovarsko srijemska"],
  ["Imotski", "splitsko dalmatinska"],
  ["Ivanec", "varazdinska"],
  ["Ivanić-Grad", "zagrebacka"],
  ["Jablanovec", "zagrebacka"],
  ["Jasenice", "zadarska"],
  ["Jasenovac", "sisacko moslavacka"],
  ["Jastrebarsko", "zagrebacka"],
  ["Jelsa", "splitsko dalmatinska"],
  ["Jesenje", "krapinsko zagorska"],
  ["Ježdovec", "grad zagreb"],
  ["Josipdol", "karlovacka"],
  ["Josipovac", "osjecko baranjska"],
  ["Jelsa", "splitsko dalmatinska"],
  ["Juršići", "istarska"],
  ["Karlobag", "licko senjska"],
  ["Karlovac", "karlovacka"],
  ["Kaštelir - Labinci - Castelliere-S. Domenica", "istarska"],
  ["Kaštela", "splitsko dalmatinska"],
  ["Kistanje", "sibensko kninska"],
  ["Klanjec", "krapinsko zagorska"],
  ["Klana", "primorsko goranska"],
  ["Klek", "dubrovacko neretvanska"],
  ["Klenovnik", "varazdinska"],
  ["Klis", "splitsko dalmatinska"],
  ["Kloštar Ivanić", "zagrebacka"],
  ["Kloštar Podravski", "koprivnicko krizevacka"],
  ["Knin", "sibensko kninska"],
  ["Konjščina", "krapinsko zagorska"],
  ["Koprivnica", "koprivnicko krizevacka"],
  ["Koprivnički Bregi", "koprivnicko krizevacka"],
  ["Koprivnički Ivanec", "koprivnicko krizevacka"],
  ["Korčula", "dubrovacko neretvanska"],
  ["Kostrena", "primorsko goranska"],
  ["Kotoriba", "medimurska"],
  ["Kraljevica", "primorsko goranska"],
  ["Krapina", "krapinsko zagorska"],
  ["Krapinske Toplice", "krapinsko zagorska"],
  ["Kravarsko", "zagrebacka"],
  ["Križ", "zagrebacka"],
  ["Križevci", "koprivnicko krizevacka"],
  ["Krk", "primorsko goranska"],
  ["Kršan", "istarska"],
  ["Kumrovec", "krapinsko zagorska"],
  ["Kutina", "sisacko moslavacka"],
  ["Kutjevo", "pozega slavonska"],
  ["Labin", "istarska"],
  ["Lančić-Knapić", "zagrebacka"],
  ["Lastovo", "dubrovacko neretvanska"],
  ["Lećevica", "splitsko dalmatinska"],
  ["Lekenik", "sisacko moslavacka"],
  ["Lepoglava", "varazdinska"],
  ["Levanjska Varoš", "osjecko baranjska"],
  ["Lipik", "pozega slavonska"],
  ["Lipovljani", "sisacko moslavacka"],
  ["Ližnjan - Lisignano", "istarska"],
  ["Lokve", "primorsko goranska"],
  ["Lovas", "vukovarsko srijemska"],
  ["Lovinac", "licko senjska"],
  ["Luka", "zagrebacka"],
  ["Lukavac", "viroviticko podravska"],
  ["Lučko", "grad zagreb"],
  ["Lumbarda", "dubrovacko neretvanska"],
  ["Ljubešćica", "varazdinska"],
  ["Mače", "krapinsko zagorska"],
  ["Makarska", "splitsko dalmatinska"],
  ["Mali Lošinj", "primorsko goranska"],
  ["Mali Bukovec", "varazdinska"],
  ["Marina", "splitsko dalmatinska"],
  ["Marijanci", "osjecko baranjska"],
  ["Marija Gorica", "zagrebacka"],
  ["Martijanec", "varazdinska"],
  ["Matulji", "primorsko goranska"],
  ["Medulin", "istarska"],
  ["Metković", "dubrovacko neretvanska"],
  ["Mikanovci", "vukovarsko srijemska"],
  ["Mikleuš", "viroviticko podravska"],
  ["Milanovac", "bjelovarsko bilogorska"],
  ["Milna", "splitsko dalmatinska"],
  ["Molve", "koprivnicko krizevacka"],
  ["Momjan", "istarska"],
  ["Motovun - Montana", "istarska"],
  ["Mrkopalj", "primorsko goranska"],
  ["Murter-Kornati", "sibensko kninska"],
  ["Našice", "osjecko baranjska"],
  ["Nedelišće", "medimurska"],
  ["Nerežišća", "splitsko dalmatinska"],
  ["Netretić", "karlovacka"],
  ["Nin", "zadarska"],
  ["Nova Gradiška", "brodsko posavska"],
  ["Nova Kapela", "brodsko posavska"],
  ["Nova Rača", "bjelovarsko bilogorska"],
  ["Nova Bukovica", "viroviticko podravska"],
  ["Novalja", "licko senjska"],
  ["Novigrad", "istarska"],
  ["Novigrad Podravski", "koprivnicko krizevacka"],
  ["Novska", "sisacko moslavacka"],
  ["Novi Marof", "varazdinska"],
  ["Novi Vinodolski", "primorsko goranska"],
  ["Obrovac", "zadarska"],
  ["Ogulin", "karlovacka"],
  ["Omiš", "splitsko dalmatinska"],
  ["Omišalj", "primorsko goranska"],
  ["Opatija", "primorsko goranska"],
  ["Oprtalj - Portole", "istarska"],
  ["Opuzen", "dubrovacko neretvanska"],
  ["Orebić", "dubrovacko neretvanska"],
  ["Oriovac", "brodsko posavska"],
  ["Orle", "zagrebacka"],
  ["Oroslavje", "krapinsko zagorska"],
  ["Osijek", "osjecko baranjska"],
  ["Otok", "vukovarsko srijemska"],
  ["Otočac", "licko senjska"],
  ["Ozalj", "karlovacka"],
  ["Pag", "zadarska"],
  ["Pakoštane", "zadarska"],
  ["Pakrac", "pozega slavonska"],
  ["Pazin", "istarska"],
  ["Petrinja", "sisacko moslavacka"],
  ["Petrijevci", "osjecko baranjska"],
  ["Petrovsko", "krapinsko zagorska"],
  ["Pirovac", "sibensko kninska"],
  ["Pitomača", "viroviticko podravska"],
  ["Pićan", "istarska"],
  ["Ploče", "dubrovacko neretvanska"],
  ["Podbablje", "splitsko dalmatinska"],
  ["Podcrkavlje", "brodsko posavska"],
  ["Podgora", "splitsko dalmatinska"],
  ["Podravska Moslavina", "osjecko baranjska"],
  ["Podstrana", "splitsko dalmatinska"],
  ["Pojezerje", "dubrovacko neretvanska"],
  ["Poličnik", "zadarska"],
  ["Popovača", "sisacko moslavacka"],
  ["Poreč - Parenzo", "istarska"],
  ["Povljana", "zadarska"],
  ["Požega", "pozega slavonska"],
  ["Pregrada", "krapinsko zagorska"],
  ["Preko", "zadarska"],
  ["Prelog", "medimurska"],
  ["Primorski Dolac", "splitsko dalmatinska"],
  ["Primošten", "sibensko kninska"],
  ["Privlaka", "zadarska"],
  ["Privlaka (Vukovar-Sirmium)", "vukovarsko srijemska"],
  ["Proložac", "splitsko dalmatinska"],
  ["Promina", "sibensko kninska"],
  ["Pula - Pola", "istarska"],
  ["Punat", "primorsko goranska"],
  ["Pušća", "zagrebacka"],
  ["Rab", "primorsko goranska"],
  ["Rakovica", "karlovacka"],
  ["Rasinja", "koprivnicko krizevacka"],
  ["Rastovac", "bjelovarsko bilogorska"],
  ["Raša", "istarska"],
  ["Ražanac", "zadarska"],
  ["Rešetari", "brodsko posavska"],
  ["Ribnik", "karlovacka"],
  ["Rijeka", "primorsko goranska"],
  ["Rogoznica", "sibensko kninska"],
  ["Rovišće", "bjelovarsko bilogorska"],
  ["Rovinj - Rovigno", "istarska"],
  ["Ružić", "sibensko kninska"],
  ["Saborsko", "karlovacka"],
  ["Sali", "zadarska"],
  ["Samobor", "zagrebacka"],
  ["Satnica Đakovačka", "osjecko baranjska"],
  ["Selnica", "medimurska"],
  ["Selca", "splitsko dalmatinska"],
  ["Semeljci", "osjecko baranjska"],
  ["Senj", "licko senjska"],
  ["Seget", "splitsko dalmatinska"],
  ["Sibinj", "brodsko posavska"],
  ["Sinj", "splitsko dalmatinska"],
  ["Sisak", "sisacko moslavacka"],
  ["Skrad", "primorsko goranska"],
  ["Skradin", "sibensko kninska"],
  ["Slatina", "viroviticko podravska"],
  ["Slavonski Brod", "brodsko posavska"],
  ["Slavonski Šamac", "brodsko posavska"],
  ["Slivno", "dubrovacko neretvanska"],
  ["Sokolovac", "koprivnicko krizevacka"],
  ["Solin", "splitsko dalmatinska"],
  ["Sopje", "viroviticko podravska"],
  ["Split", "splitsko dalmatinska"],
  ["Srinjine", "splitsko dalmatinska"],
  ["Stankovci", "zadarska"],
  ["Starigrad", "splitsko dalmatinska"],
  ["Stari Jankovci", "vukovarsko srijemska"],
  ["Stari Mikanovci", "vukovarsko srijemska"],
  ["Staro Petrovo Selo", "brodsko posavska"],
  ["Ston", "dubrovacko neretvanska"],
  ["Strahoninec", "medimurska"],
  ["Strizivojna", "osjecko baranjska"],
  ["Supetar", "splitsko dalmatinska"],
  ["Sućuraj", "splitsko dalmatinska"],
  ["Sveta Nedelja", "istarska"],
  ["Sveta Marija", "medimurska"],
  ["Sveti Ivan Zelina", "zagrebacka"],
  ["Sveti Križ Začretje", "krapinsko zagorska"],
  ["Svetvinčenat", "istarska"],
  ["Šibenik", "sibensko kninska"],
  ["Škabrnja", "zadarska"],
  ["Šodolovci", "osjecko baranjska"],
  ["Šolta", "splitsko dalmatinska"],
  ["Špišić Bukovica", "viroviticko podravska"],
  ["Štrigova", "medimurska"],
  ["Tar-Vabriga - Torre-Abrega", "istarska"],
  ["Tisno", "sibensko kninska"],
  ["Tkon", "zadarska"],
  ["Tompojevci", "vukovarsko srijemska"],
  ["Tordinci", "vukovarsko srijemska"],
  ["Tounj", "karlovacka"],
  ["Tribunj", "sibensko kninska"],
  ["Trilj", "splitsko dalmatinska"],
  ["Trnava", "osjecko baranjska"],
  ["Trpanj", "dubrovacko neretvanska"],
  ["Trpinja", "vukovarsko srijemska"],
  ["Trogir", "splitsko dalmatinska"],
  ["Tupik", "viroviticko podravska"],
  ["Tučepi", "splitsko dalmatinska"],
  ["Tvrđavica", "osjecko baranjska"],
  ["Udbina", "licko senjska"],
  ["Umag - Umago", "istarska"],
  ["Unešić", "sibensko kninska"],
  ["Uskoplje", "splitsko dalmatinska"],
  ["Valpovo", "osjecko baranjska"],
  ["Varaždin", "varazdinska"],
  ["Varaždinske Toplice", "varazdinska"],
  ["Velika", "pozega slavonska"],
  ["Velika Gorica", "zagrebacka"],
  ["Velika Ludina", "sisacko moslavacka"],
  ["Velika Pisanica", "bjelovarsko bilogorska"],
  ["Veliki Grđevac", "bjelovarsko bilogorska"],
  ["Veliki Bukovec", "varazdinska"],
  ["Veliki Žitnik", "licko senjska"],
  ["Vinkovci", "vukovarsko srijemska"],
  ["Vinica", "varazdinska"],
  ["Vir", "zadarska"],
  ["Višnjan - Visignano", "istarska"],
  ["Viškovo", "primorsko goranska"],
  ["Vižinada - Visinada", "istarska"],
  ["Visoko", "varazdinska"],
  ["Vižinada", "istarska"],
  ["Virovitica", "viroviticko podravska"],
  ["Vis", "splitsko dalmatinska"],
  ["Vladislavci", "osjecko baranjska"],
  ["Vodice", "sibensko kninska"],
  ["Vodnjan - Dignano", "istarska"],
  ["Vojnić", "karlovacka"],
  ["Vrbje", "brodsko posavska"],
  ["Vrbnik", "primorsko goranska"],
  ["Vrgorac", "splitsko dalmatinska"],
  ["Vrlika", "splitsko dalmatinska"],
  ["Vrpolje", "brodsko posavska"],
  ["Vrsar - Orsera", "istarska"],
  ["Vukovar", "vukovarsko srijemska"],
  ["Zabok", "krapinsko zagorska"],
  ["Zadar", "zadarska"],
  ["Zagreb", "grad zagreb"],
  ["Zažablje", "dubrovacko neretvanska"],
  ["Zdenci", "viroviticko podravska"],
  ["Zemunik Donji", "zadarska"],
  ["Zlatar", "krapinsko zagorska"],
  ["Zlatar Bistrica", "krapinsko zagorska"],
  ["Zmaj", "osjecko baranjska"],
  ["Zrinski Topolovac", "bjelovarsko bilogorska"],
  ["Žakanje", "karlovacka"],
  ["Žminj", "istarska"],
  ["Žumberak", "zagrebacka"],
  ["Župa dubrovačka", "dubrovacko neretvanska"],
  ["City of Zagreb", "grad zagreb"],
]);
